### ISSUE TITLE
执行 pnpm run dev 后报错，请问是什么原因 

### ISSUE THREAD

**Issue by re2x** [OLIVERgZzy/TCM-Body-Constitution-Test#1]
main分支，commit f21b57e3907d57c4e830c005fdc8825c033b28cc
先执行 pnpm install 
再执行 pnpm run dev 后报错，请问是什么原因       

``` shell
> @ dev TCM-Body-Constitution-Test
> nuxt dev                                                          13:38:16
Nuxi 3.3.2                                                            13:38:16
Nuxt 3.3.2 with Nitro 2.3.2                                           13:38:16

 ERROR  (0 , _nuxt.defineNuxtConfig) is not a function                13:38:17
  at nuxt.config.ts:19:43
  at Object.jiti (node_modules/.pnpm/registry.npmmirror.com+jiti@1.18.2/node_modules/jiti/dist/jiti.js:1:245784)
  at resolveConfig (node_modules/.pnpm/registry.npmmirror.com+c12@1.2.0/node_modules/c12/dist/index.mjs:271:24)
  at loadConfig (node_modules/.pnpm/registry.npmmirror.com+c12@1.2.0/node_modules/c12/dist/index.mjs:113:40)
  at async loadNuxtConfig (node_modules/.pnpm/registry.npmmirror.com+@nuxt+kit@3.3.2/node_modules/@nuxt/kit/dist/index.mjs:486:18)
  at async Object.invoke (node_modules/.pnpm/registry.npmmirror.com+nuxi@3.3.2/node_modules/nuxi/dist/chunks/dev.mjs:6765:20)
  at async _main (node_modules/.pnpm/registry.npmmirror.com+nuxi@3.3.2/node_modules/nuxi/dist/cli.mjs:49:20)

 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by chihyungchang** [comment]
你好，我运行不报错，你可以清理node_modules重新再试
我的系统是mac，node版本是v16.14.2，pnpm版本是6.28.0
